version: '3.8'

services:
  entries_mongodb:
    image: mongo:latest
    container_name: entries_mongodb
    restart: always
    env_file:
      - env_files/.mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      mongo-network:
        aliases:
          - entries_mongodb
  
  mongo_express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - env_files/.mongo-express.env
    networks:
      mongo-network:
        aliases:
          - mongo_express

networks:
  mongo-network: